name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Install Dependencies
        run: npm install

      - name: Fix ESLint Permissions
        run: chmod +x node_modules/.bin/eslint

      - name: Run ESLint
        run: npx eslint . --fix

  gitstream:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Install GitStream
        run: npm install linear-b/gitstream --save-dev

      - name: Run GitStream
        run: npx gitstream

  automate-pr-checks:
    runs-on: ubuntu-latest
    needs: gitstream

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run GitHub Script for PR Checks
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const sha = context.payload.pull_request.head.sha;
            const conclusion = 'success'; // or 'failure' based on your checks

            await github.checks.create({
              ...context.repo,
              name: 'Custom PR Checks',
              head_sha: sha,
              status: 'completed',
              conclusion: conclusion,
              output: {
                title: 'Check Summary',
                summary: 'All checks passed.',
                text: 'This PR has passed all checks.'
              }
            });
