name: gitStream workflow automation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gitStream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Node.js dependencies for gitStream
      - name: Install Node.js dependencies
        run: npm install

      # Evaluate GitStream Rules
      - name: Evaluate GitStream Rules
        uses: linear-b/gitstream-github-action@v3
        id: rules-engine
        with:
          full_repository: ${{ github.repository }}
          head_ref: ${{ github.head_ref }}
          base_ref: ${{ github.base_ref }}

      # Handle Results (if necessary)
      - name: Check results
        if: ${{ steps.rules-engine.outputs.conclusion == 'failure' }}
        run: echo "GitStream rule evaluation failed"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Node.js dependencies to run ESLint
      - name: Install dependencies
        run: npm ci

      # Run ESLint
      - name: Run ESLint
        id: lint
        run: npm run lint -- --format checkstyle --output-file eslint-report.xml

      # Upload ESLint report
      - name: Upload ESLint report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: eslint-report.xml

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Node.js dependencies for testing
      - name: Install Node.js dependencies
        run: npm install

      # Run tests
      - name: Run Unit Tests
        run: npm test -- --ci --reporter=jest-junit --outputFile=unit-test-results.xml

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: unit-test-results.xml
