name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run GitStream Rules
        uses: linear-b/gitstream-github-action@v2  # Change to a specific commit or version
        id: rules-engine

      - name: Run Actions GitHub Script
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const headSha = context.payload.pull_request.head.sha; // Ensure this is defined
            if (!headSha) {
              throw new Error('No head SHA available for the pull request.');
            }
            // Your script logic here
            console.log(`Head SHA: ${headSha}`);
            
      - name: Complete Status Check
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const headSha = context.payload.pull_request.head.sha; // Ensure this is defined
            const conclusion = 'success'; // Or 'failure' based on your logic
            await github.checks.create({
              ...context.repo,
              name: 'ESLint',
              head_sha: headSha,
              status: 'completed',
              conclusion,
              output: {
                title: 'ESLint Check',
                summary: 'ESLint issues reported in this run',
                text: 'Check the ESLint report for detailed errors or warnings.'
              }
            });

