name: GitStream workflow automation

on:
  pull_request:
    branches:
      - main

jobs:
  gitStream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run GitStream
        uses: linear-b/gitstream-github-action@v1
        with:
          cm: './gitstream.cm'  # Ensuring correct path to the gitstream.cm file

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: npm test -- --ci --reporter=jest-junit --outputFile=unit-test-results.xml

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: unit-test-results.xml
