name: gitStream workflow automation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  gitStream:
    name: "gitStream workflow automation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Node.js dependencies
        run: npm install

      - name: Evaluate GitStream Rules
        uses: linear-b/gitstream-github-action@v2
        id: rules-engine
        with:
          full_repository: ${{ github.repository }}
          head_ref: ${{ github.head_ref }}
          base_ref: ${{ github.base_ref }}
          client_payload: ${{ github.event.client_payload }}
          installation_id: ${{ github.event.installation_id }}
          resolver_url: ${{ github.event.resolver_url }}
          resolver_token: ${{ github.event.resolver_token }}

  lint:
    name: "ESLint Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false  # Fail the workflow if linting errors occur
